"""Produce the updated ECMB MagIC contribution (17072) carrying the pole.

The published contribution earthref.org/MagIC/17072 (Swanson-Hysell et al., 2021,
DOI 10.1029/2021TC006751) archives the sites, samples, specimens, measurements,
and ages of the East-Central Minnesota Batholith study but has **no
location-level pole result**. This script downloads 17072 and produces a single
combined MagIC upload file that is **identical to the published contribution
except that the paleomagnetic pole is added to the `locations` table** on the
`ECMB` location row.

Nothing else is changed: the sites table (all 90 multi-component site rows), the
samples, specimens, measurements, and ages tables all pass through unchanged, and
the published location metadata (age, coordinates, lithology, etc.) is preserved.
The only edit is setting the pole-result columns on the location row.

The pole itself (medium-coercivity / magnetite ChRM of the NE-trending dikes,
site a95 < 8 deg, N = 23; 20.5 degN, 265.8 degE, A95 4.5, K 45.6) is taken from
``../locations.txt``, which is generated by ``ECMB_build_contribution.py``.

Output: ``../Swanson-Hysell2021_updated_ECMB_<date>.txt`` in the 1779 pole
folder, ready to upload to MagIC as an update of contribution 17072.

Note: this downloads ~2.9 MB (incl. the measurement table) from MagIC; run with a
network connection. If MagIC is unreachable it falls back to the published tables
in the source repo (``2021_ECMB/data/rockmag_pmag_MagIC``). Do not commit the
large merged measurements file to git history.
"""

import shutil
import tempfile
from pathlib import Path

import pandas as pd
import pmagpy.ipmag as ipmag

MAGIC_ID = '17072'
HERE = Path(__file__).parent
ECMB_DIR = HERE.parent                       # data/1779_East_Central_Minnesota_Batholith
LOCATION = 'ECMB'                            # 17072 location that carries the pole

# fallback source if MagIC cannot be reached (published 17072 tables)
LOCAL_SRC = Path('/Users/penokean/0000_GitHub/2021_ECMB/data/rockmag_pmag_MagIC')

# columns that make up the pole result added to the location row
POLE_COLS = ['result_type', 'result_name', 'result_quality', 'method_codes',
             'citations', 'dir_tilt_correction', 'pole_lat', 'pole_lon',
             'pole_alpha95', 'pole_k', 'pole_n_sites', 'pole_n_samples',
             'sites', 'description']


def read_magic(path):
    return pd.read_csv(path, sep='\t', skiprows=1, dtype=str).fillna('')


def write_magic(path, table_type, df):
    with open(path, 'w') as f:
        f.write(f'tab delimited\t{table_type}\n')
    df.to_csv(path, sep='\t', index=False, mode='a')


def fetch_contribution(work):
    """Download 17072 into ``work`` and unpack it; fall back to the local repo."""
    try:
        ok, msg = ipmag.download_magic_from_id(MAGIC_ID, directory=str(work))
        if not ok:
            raise RuntimeError(msg)
        ipmag.download_magic(infile=f'magic_contribution_{MAGIC_ID}.txt',
                             dir_path=str(work), input_dir_path=str(work),
                             print_progress=False)
        print(f'-I- downloaded contribution {MAGIC_ID} from MagIC')
    except Exception as ex:
        print(f'-W- could not download {MAGIC_ID} from MagIC ({ex});')
        print(f'-W- falling back to local published tables in {LOCAL_SRC}')
        for name in ('sites.txt', 'locations.txt', 'samples.txt',
                     'specimens.txt', 'measurements.txt', 'ages.txt'):
            src = LOCAL_SRC / name
            if src.exists():
                shutil.copy(src, work / name)


def main():
    work = Path(tempfile.mkdtemp(prefix='magic17072_update_'))
    fetch_contribution(work)

    # ---- locations: add the pole result onto the ECMB row -----------------
    loc = read_magic(work / 'locations.txt')
    pole = read_magic(ECMB_DIR / 'locations.txt').iloc[0]

    for col in POLE_COLS:
        if col not in loc.columns:
            loc[col] = ''
    mask = loc['location'] == LOCATION
    if not mask.any():
        raise SystemExit(f"location '{LOCATION}' not found in {MAGIC_ID}")
    for col in POLE_COLS:
        loc.loc[mask, col] = pole[col]
    write_magic(work / 'locations.txt', 'locations', loc)

    # sites / samples / specimens / measurements / ages pass through unchanged.
    sites = read_magic(work / 'sites.txt')
    print(f'Updated contribution {MAGIC_ID} (identical to published + pole):')
    print(f'  sites unchanged: {len(sites)} rows')
    print(f'  pole on "{LOCATION}": {pole["pole_lat"]}N {pole["pole_lon"]}E '
          f'A95={pole["pole_alpha95"]} K={pole["pole_k"]} '
          f'N={pole["pole_n_sites"]} ({pole["pole_n_samples"]} samples)')

    result = ipmag.upload_magic(dir_path=str(work), input_dir_path=str(work))

    # upload_magic writes the combined upload file (named <Location>_<date>.txt)
    # even when the optional online validation step cannot reach MagIC. Use the
    # returned path if validation succeeded; otherwise recover the prepared file.
    upload_file = result[0]
    if not upload_file:
        known = {'sites.txt', 'samples.txt', 'specimens.txt', 'measurements.txt',
                 'locations.txt', 'ages.txt', 'contribution.txt', 'upload.txt',
                 f'magic_contribution_{MAGIC_ID}.txt'}
        prepared = [p for p in work.glob('*.txt') if p.name not in known]
        if not prepared:
            raise SystemExit(f'upload_magic failed: {result[1]}')
        upload_file = str(prepared[0])
        print(f'-W- online validation unavailable ({result[1]}); the combined '
              f'file was still prepared. Validate it on upload to MagIC.')

    dest = ECMB_DIR / ('Swanson-Hysell2021_updated_' + Path(upload_file).name)
    shutil.copy(upload_file, dest)
    print(f'Wrote updated contribution: {dest} '
          f'({dest.stat().st_size / 1e6:.1f} MB)')
    shutil.rmtree(work, ignore_errors=True)


if __name__ == '__main__':
    main()
